behaviors:
  MyAgent:
    trainer_type: ppo
    max_steps: 100000
    time_horizon: 64
    summary_freq: 5000
    network_settings:
      num_layers: 2
      hidden_units: 64
    hyperparameters:
      learning_rate: 3.0e-4
      batch_size: 1024
      buffer_size: 4096
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0